### ISSUE TITLE
Development Environment Configuration

### ISSUE THREAD

**Issue by rockandfire** [ou-cs5213-sp24/capstone-management-system#6]
Create documentation for the following:
  • Installation of Python, Django, and other dependencies on development machines.
  • Setup of a virtual environment for each developer to maintain project-specific dependencies separately from
  the global environment.
  • Establishment of a version control system with an initialized repository and properly configured .gitignore file.

Definition of Done:
• A developer can successfully compile the Django project after following the startup guide start to finish.

**Comment by TorrentialFire** [comment]
Try breaking this up into multiple issues based on the type of work to be completed. Instead of "deliverables" create a "definition of done" for the issue/task which describes the outcome if the task if performed successfully.

A good thing to look out for is conjunctions like "and" which indicate that you may be combining issues/tasks. Try to break the milestone down so that each member of your team has some issues assigned to them, rather than the whole team assigned to 1 issue.
